### ISSUE TITLE
Pickled Models use too-old SKLearn

### ISSUE THREAD

**Issue by MattWellie** [andrewSharo/StrVCTVRE#8]
We'd like to start using this tool in our SV annotation pipeline, but I'm having some installation issues. The pickled models use a super old version of sklearn, and when loading the contents I run into this error:

`ModuleNotFoundError: No module named 'sklearn.ensemble.forest'`

From hunting around this module was renamed in a sklearn version released in 2019, so anything since then won't work. To get a version of sklearn old enough to open these files we'd have to compile from source, as compatibility doesn't seem to go back far enough. 

I appreciate this is optimistic, but would you be able to regenerate these files, or provide instructions on how they were generated, so that we can use this tool in an up-to-date environment?

**Comment by andrewSharo** [comment]
Hi Matt,
Thanks for pointing this out! Yes, these files are from an ancient version of sklearn. I should be able to regenerate these files. Give me until the end of the week and I'll update you again.
Andrew

**Comment by andrewSharo** [comment]
Hi Matt,
Thanks for your patience. I've updated the pickled models so that there is now just a single model (I should have done this long ago). The newest sklearn version that I could get to work with all the other packages is 1.0.2. Let me know if this works. If not, I can also send you a model created using sklearn 1.3. Additionally, if you tell me which version you're using, I can probably make a pickled model from that version. But hopefully the 1.0.2 version will be compatible.
Andrew

**Comment by MattWellie** [comment]
@andrewSharo  AWESOME, absolute hero 👑 

I've managed a build and test with the latest version!
