### ISSUE TITLE
Online annotation service not working

### ISSUE THREAD

**Issue by jsquaredosquared** [andrewSharo/StrVCTVRE#9]
![image](https://github.com/andrewSharo/StrVCTVRE/assets/89121419/8a41485e-baf6-4ce0-8c65-2540f0498bef)

Thanks for the tool.

It appears there is a problem with the server that is preventing it from fulfilling the request. Is there anything you can do to fix this?

**Comment by andrewSharo** [comment]
Hi @jsquaredosquared,
Thanks so much for bringing up this issue. I believe this issue was caused by no space left on the server. We've cleared more space. I tested it and all appears to be working now. Please let me know if you run into further issues.

Andrew

**Comment by jsquaredosquared** [comment]
Hey @andrewSharo,

Thanks for trying to fix the issue. I can annotate the example bed file. However, I am still unable to annotate one of bed files, even though the file size (~2.5 MB) is below the stipulated size limit (50 MB) -- see the video below. 

My BED file does contain around 100,000 SVs. I can only annotate the SVs successfully if I break up the file and upload them in chunks. Is there a limit on the number of SVs that can be annotated with the online web service? If so, it might be good to mention it somewhere.

Thanks again.

https://github.com/andrewSharo/StrVCTVRE/assets/89121419/4e119cf1-04ab-4a59-bd8c-7c93a1ccd9ae

**Comment by andrewSharo** [comment]
Hi Jeff,

Thanks for this video and for your persistence. It turns out our servers were updated recently and that reset the max file upload size to 2mb. I just fixed this, and now I'm able to annotate an 8mb bed file. Can you try again?

In terms of max SVs, there probably is a max number but it's hard to predict. I think 100k should be okay.

Let me know if you find more bugs :)

Andrew
